-- Задание 2. Выполнить в новой базе demo_exam_2027.
BEGIN;

CREATE TABLE counterparties (
    id varchar(20) PRIMARY KEY,
    name varchar(200) NOT NULL CHECK (btrim(name) <> ''),
    inn varchar(20) NOT NULL DEFAULT '',
    address text NOT NULL DEFAULT '',
    phone varchar(30) NOT NULL DEFAULT '',
    type varchar(30) NOT NULL CHECK (type IN ('Покупатель', 'Поставщик', 'Изготовитель'))
);

CREATE TABLE units (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) NOT NULL UNIQUE
);

CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    production_code varchar(30) UNIQUE,
    name varchar(200) NOT NULL,
    unit_id integer NOT NULL REFERENCES units(id)
);

CREATE TABLE materials (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    name varchar(200) NOT NULL,
    unit_id integer NOT NULL REFERENCES units(id),
    unit_price numeric(14,2) NOT NULL CHECK (unit_price >= 0)
);

CREATE TABLE operations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    name varchar(200) NOT NULL,
    unit_id integer NOT NULL REFERENCES units(id),
    unit_price numeric(14,2) NOT NULL CHECK (unit_price >= 0)
);

CREATE TABLE specifications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL UNIQUE REFERENCES products(id),
    name varchar(200) NOT NULL,
    manufacturer_id varchar(20) NOT NULL REFERENCES counterparties(id)
);

CREATE TABLE specification_materials (
    specification_id integer NOT NULL REFERENCES specifications(id),
    material_id integer NOT NULL REFERENCES materials(id),
    quantity numeric(14,6) NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (specification_id, material_id)
);

CREATE TABLE specification_operations (
    specification_id integer NOT NULL REFERENCES specifications(id),
    operation_id integer NOT NULL REFERENCES operations(id),
    quantity numeric(14,6) NOT NULL CHECK (quantity > 0),
    time_norm numeric(14,6) NOT NULL CHECK (time_norm > 0),
    PRIMARY KEY (specification_id, operation_id)
);

CREATE TABLE departments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(100) NOT NULL CHECK (btrim(login) <> '' AND login = btrim(login)),
    password_hash text NOT NULL,
    role varchar(30) NOT NULL CHECK (role IN ('Администратор', 'Пользователь')),
    is_blocked boolean NOT NULL DEFAULT false,
    failed_attempts integer NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 3)
);
CREATE UNIQUE INDEX users_login_unique ON users (lower(login));

CREATE TABLE customer_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar(30) NOT NULL UNIQUE,
    order_date date NOT NULL,
    customer_id varchar(20) NOT NULL REFERENCES counterparties(id),
    executor_id varchar(20) NOT NULL REFERENCES counterparties(id)
);

CREATE TABLE customer_order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES customer_orders(id),
    product_id integer NOT NULL REFERENCES products(id),
    quantity numeric(14,6) NOT NULL CHECK (quantity > 0),
    sale_price numeric(14,2) NOT NULL CHECK (sale_price >= 0),
    discount_amount numeric(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    CHECK (discount_amount <= quantity * sale_price),
    UNIQUE (order_id, product_id)
);

CREATE TABLE production_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number varchar(30) NOT NULL UNIQUE,
    order_date date NOT NULL,
    start_date date NOT NULL,
    customer_order_id integer NOT NULL REFERENCES customer_orders(id),
    department_id integer NOT NULL REFERENCES departments(id),
    executor_user_id integer NOT NULL REFERENCES users(id)
);

CREATE TABLE production_order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id integer NOT NULL REFERENCES production_orders(id),
    specification_id integer NOT NULL REFERENCES specifications(id),
    quantity numeric(14,6) NOT NULL CHECK (quantity > 0),
    UNIQUE (production_order_id, specification_id)
);

CREATE TABLE notes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL CHECK (btrim(title) <> ''),
    content text NOT NULL,
    id_user integer NOT NULL REFERENCES users(id),
    created_at date NOT NULL DEFAULT CURRENT_DATE
);

COMMIT;
