--
-- PostgreSQL database dump
--


-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: counterparties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.counterparties (
    id character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    inn character varying(20) DEFAULT ''::character varying NOT NULL,
    address text DEFAULT ''::text NOT NULL,
    phone character varying(30) DEFAULT ''::character varying NOT NULL,
    type character varying(30) NOT NULL,
    CONSTRAINT counterparties_name_check CHECK ((btrim((name)::text) <> ''::text)),
    CONSTRAINT counterparties_type_check CHECK (((type)::text = ANY ((ARRAY['Покупатель'::character varying, 'Поставщик'::character varying, 'Изготовитель'::character varying])::text[])))
);


--
-- Name: customer_order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_order_items (
    id integer NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity numeric(14,6) NOT NULL,
    sale_price numeric(14,2) NOT NULL,
    discount_amount numeric(14,2) DEFAULT 0 NOT NULL,
    CONSTRAINT customer_order_items_check CHECK ((discount_amount <= (quantity * sale_price))),
    CONSTRAINT customer_order_items_discount_amount_check CHECK ((discount_amount >= (0)::numeric)),
    CONSTRAINT customer_order_items_quantity_check CHECK ((quantity > (0)::numeric)),
    CONSTRAINT customer_order_items_sale_price_check CHECK ((sale_price >= (0)::numeric))
);


--
-- Name: customer_order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_orders (
    id integer NOT NULL,
    number character varying(30) NOT NULL,
    order_date date NOT NULL,
    customer_id character varying(20) NOT NULL,
    executor_id character varying(20) NOT NULL
);


--
-- Name: customer_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.materials (
    id integer NOT NULL,
    code character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    unit_id integer NOT NULL,
    unit_price numeric(14,2) NOT NULL,
    CONSTRAINT materials_unit_price_check CHECK ((unit_price >= (0)::numeric))
);


--
-- Name: materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notes (
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    id_user integer NOT NULL,
    created_at date DEFAULT CURRENT_DATE NOT NULL,
    CONSTRAINT notes_title_check CHECK ((btrim((title)::text) <> ''::text))
);


--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.operations (
    id integer NOT NULL,
    code character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    unit_id integer NOT NULL,
    unit_price numeric(14,2) NOT NULL,
    CONSTRAINT operations_unit_price_check CHECK ((unit_price >= (0)::numeric))
);


--
-- Name: operations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.operations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: specification_materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.specification_materials (
    specification_id integer NOT NULL,
    material_id integer NOT NULL,
    quantity numeric(14,6) NOT NULL,
    CONSTRAINT specification_materials_quantity_check CHECK ((quantity > (0)::numeric))
);


--
-- Name: specification_operations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.specification_operations (
    specification_id integer NOT NULL,
    operation_id integer NOT NULL,
    quantity numeric(14,6) NOT NULL,
    time_norm numeric(14,6) NOT NULL,
    CONSTRAINT specification_operations_quantity_check CHECK ((quantity > (0)::numeric)),
    CONSTRAINT specification_operations_time_norm_check CHECK ((time_norm > (0)::numeric))
);


--
-- Name: specifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.specifications (
    id integer NOT NULL,
    product_id integer NOT NULL,
    name character varying(200) NOT NULL,
    manufacturer_id character varying(20) NOT NULL
);


--
-- Name: order_costs; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.order_costs AS
 WITH material_cost AS (
         SELECT sm.specification_id,
            sum((sm.quantity * m.unit_price)) AS cost
           FROM (public.specification_materials sm
             JOIN public.materials m ON ((m.id = sm.material_id)))
          GROUP BY sm.specification_id
        ), operation_cost AS (
         SELECT so.specification_id,
            sum(((so.quantity * so.time_norm) * op.unit_price)) AS cost
           FROM (public.specification_operations so
             JOIN public.operations op ON ((op.id = so.operation_id)))
          GROUP BY so.specification_id
        )
 SELECT o.id AS order_id,
    o.number,
    o.order_date,
    c.name AS customer,
    round(COALESCE(sum((i.quantity * COALESCE(mc.cost, (0)::numeric))), (0)::numeric), 2) AS materials_cost,
    round(COALESCE(sum((i.quantity * COALESCE(oc.cost, (0)::numeric))), (0)::numeric), 2) AS operations_cost,
    round(COALESCE(sum((i.quantity * (COALESCE(mc.cost, (0)::numeric) + COALESCE(oc.cost, (0)::numeric)))), (0)::numeric), 2) AS total_cost,
    round(COALESCE(sum(((i.quantity * i.sale_price) - i.discount_amount)), (0)::numeric), 2) AS sale_total
   FROM (((((public.customer_orders o
     JOIN public.counterparties c ON (((c.id)::text = (o.customer_id)::text)))
     LEFT JOIN public.customer_order_items i ON ((i.order_id = o.id)))
     LEFT JOIN public.specifications s ON ((s.product_id = i.product_id)))
     LEFT JOIN material_cost mc ON ((mc.specification_id = s.id)))
     LEFT JOIN operation_cost oc ON ((oc.specification_id = s.id)))
  GROUP BY o.id, o.number, o.order_date, c.name;


--
-- Name: production_order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.production_order_items (
    id integer NOT NULL,
    production_order_id integer NOT NULL,
    specification_id integer NOT NULL,
    quantity numeric(14,6) NOT NULL,
    CONSTRAINT production_order_items_quantity_check CHECK ((quantity > (0)::numeric))
);


--
-- Name: production_order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.production_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: production_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.production_orders (
    id integer NOT NULL,
    number character varying(30) NOT NULL,
    order_date date NOT NULL,
    start_date date NOT NULL,
    customer_order_id integer NOT NULL,
    department_id integer NOT NULL,
    executor_user_id integer NOT NULL
);


--
-- Name: production_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.production_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.production_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id integer NOT NULL,
    code character varying(30) NOT NULL,
    production_code character varying(30),
    name character varying(200) NOT NULL,
    unit_id integer NOT NULL
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: specifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.specifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: units; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.units (
    id integer NOT NULL,
    name character varying(20) NOT NULL
);


--
-- Name: units_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.units_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying(100) NOT NULL,
    password_hash text NOT NULL,
    role character varying(30) NOT NULL,
    is_blocked boolean DEFAULT false NOT NULL,
    failed_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT users_failed_attempts_check CHECK (((failed_attempts >= 0) AND (failed_attempts <= 3))),
    CONSTRAINT users_login_check CHECK (((btrim((login)::text) <> ''::text) AND ((login)::text = btrim((login)::text)))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['Администратор'::character varying, 'Пользователь'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: counterparties; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('000000001', 'ООО "Поставка"', '', 'г.Пятигорск', '+79198634592', 'Поставщик');
INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('000000002', 'ООО "Кинотеатр Квант"', '26320045123', 'г. Железноводск, ул. Мира, 123', '+79884581555', 'Покупатель');
INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('000000008', 'ООО "Новый JDTO"', '26320045111', 'г. Железноводсу', '+79884581555', 'Покупатель');
INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('000000003', 'ООО "Ромашка"', '4140784214', 'г. Омск, ул. Строителей, 294', '+79882584546', 'Поставщик');
INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('000000009', 'ООО "Ипподром"', '5874045632', 'г. Уфа, ул. Набережная,  37', '+79627486389', 'Поставщик');
INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('000000010', 'ООО "Ассоль"', '2629011278', 'г. Калуга, ул. Пушкина, 94', '+79184572398', 'Покупатель');
INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('EXCEL-SELLER', 'ООО ТД "Вершина"', '', '', '', 'Изготовитель');
INSERT INTO public.counterparties (id, name, inn, address, phone, type) VALUES ('EXCEL-BUYER', 'ИП Томилин Александр Сергеевич', '', '', '', 'Покупатель');


--
-- Data for Name: customer_order_items; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.customer_order_items (id, order_id, product_id, quantity, sale_price, discount_amount) VALUES (1, 1, 1, 2.000000, 14120.00, 1412.00);


--
-- Data for Name: customer_orders; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.customer_orders (id, number, order_date, customer_id, executor_id) VALUES (1, '1', '2026-04-22', 'EXCEL-BUYER', 'EXCEL-SELLER');


--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.departments (id, name) VALUES (1, 'Основное подразделение');


--
-- Data for Name: materials; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.materials (id, code, name, unit_id, unit_price) VALUES (1, 'ФР-00000009', 'Столешница круглая', 1, 3250.00);
INSERT INTO public.materials (id, code, name, unit_id, unit_price) VALUES (2, 'ФР-00000013', 'Мебельная деталь 500х800', 1, 95.00);
INSERT INTO public.materials (id, code, name, unit_id, unit_price) VALUES (3, 'ФР-00000016', 'Мебельная деталь 600х800', 1, 140.00);
INSERT INTO public.materials (id, code, name, unit_id, unit_price) VALUES (4, 'ФР-00000027', 'Евровинт 6,5х5', 2, 595.00);
INSERT INTO public.materials (id, code, name, unit_id, unit_price) VALUES (5, 'ФР-00000026', 'Опора', 1, 245.00);


--
-- Data for Name: notes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.notes (id, title, content, id_user, created_at) VALUES (1, 'Конференция ИТ', 'Содержимое заметки', 2, '2027-03-15');
INSERT INTO public.notes (id, title, content, id_user, created_at) VALUES (2, 'Заказ на производство', 'Подготовить материалы для двух столов.', 1, '2027-03-16');
INSERT INTO public.notes (id, title, content, id_user, created_at) VALUES (3, 'Встреча с заказчиком', 'Обсудить сроки поставки.', 2, '2027-03-17');
INSERT INTO public.notes (id, title, content, id_user, created_at) VALUES (4, 'Проверка спецификации', 'Проверить нормы расхода материалов.', 3, '2027-03-18');
INSERT INTO public.notes (id, title, content, id_user, created_at) VALUES (5, 'Отчёт', 'Подготовить отчёт о производстве.', 1, '2027-03-19');


--
-- Data for Name: operations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.operations (id, code, name, unit_id, unit_price) VALUES (1, 'ФР-00000053', 'Сборка модулей', 3, 1400.00);
INSERT INTO public.operations (id, code, name, unit_id, unit_price) VALUES (2, 'ФР-00000052', 'Распил ДСП, МДФ и листового материала', 3, 450.00);
INSERT INTO public.operations (id, code, name, unit_id, unit_price) VALUES (3, 'ФР-00000494', 'Упаковка', 3, 950.00);


--
-- Data for Name: production_order_items; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.production_order_items (id, production_order_id, specification_id, quantity) VALUES (1, 1, 1, 2.000000);


--
-- Data for Name: production_orders; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.production_orders (id, number, order_date, start_date, customer_order_id, department_id, executor_user_id) VALUES (1, '1', '2026-04-23', '2026-04-23', 1, 1, 1);


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.products (id, code, production_code, name, unit_id) VALUES (1, 'ФР-00000034', 'НФ-00000006', 'Стол кухонный "Самобранка"', 1);


--
-- Data for Name: specification_materials; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.specification_materials (specification_id, material_id, quantity) VALUES (1, 1, 1.000000);
INSERT INTO public.specification_materials (specification_id, material_id, quantity) VALUES (1, 2, 2.000000);
INSERT INTO public.specification_materials (specification_id, material_id, quantity) VALUES (1, 3, 4.000000);
INSERT INTO public.specification_materials (specification_id, material_id, quantity) VALUES (1, 4, 0.012000);
INSERT INTO public.specification_materials (specification_id, material_id, quantity) VALUES (1, 5, 4.000000);


--
-- Data for Name: specification_operations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.specification_operations (specification_id, operation_id, quantity, time_norm) VALUES (1, 1, 1.000000, 0.750000);
INSERT INTO public.specification_operations (specification_id, operation_id, quantity, time_norm) VALUES (1, 2, 1.000000, 1.500000);
INSERT INTO public.specification_operations (specification_id, operation_id, quantity, time_norm) VALUES (1, 3, 1.000000, 0.500000);


--
-- Data for Name: specifications; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.specifications (id, product_id, name, manufacturer_id) VALUES (1, 1, 'Спецификация стола Самобранка', 'EXCEL-SELLER');


--
-- Data for Name: units; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.units (id, name) VALUES (1, 'шт');
INSERT INTO public.units (id, name) VALUES (2, 'тыс. шт');
INSERT INTO public.units (id, name) VALUES (3, 'ч');


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (id, login, password_hash, role, is_blocked, failed_attempts) VALUES (2, 'user25', 'CKN9qNfKgl8gSLut2rKR1Q==:3WFR6hBi89MKbvjsL6GbQcBMvL2BO/65lr8l8KBE4jY=', 'Пользователь', false, 0);
INSERT INTO public.users (id, login, password_hash, role, is_blocked, failed_attempts) VALUES (3, 'user26', 'dJJTtuS37F/Wfzh+/HKYww==:wi2oZgeG83IlicR0rfMK5pgE7lgNzpw+xZ48ZXvTUHc=', 'Пользователь', false, 0);
INSERT INTO public.users (id, login, password_hash, role, is_blocked, failed_attempts) VALUES (1, 'admin', 'Aqy7bd7w5lzPrQQI6j5pRA==:EctpD6BbGaRzohlBKgC7w9EZwFCXmXtCWSdN6p01QJU=', 'Администратор', false, 0);


--
-- Name: customer_order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customer_order_items_id_seq', 3, true);


--
-- Name: customer_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customer_orders_id_seq', 3, true);


--
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.departments_id_seq', 1, true);


--
-- Name: materials_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.materials_id_seq', 7, true);


--
-- Name: notes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.notes_id_seq', 7, true);


--
-- Name: operations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.operations_id_seq', 3, true);


--
-- Name: production_order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.production_order_items_id_seq', 1, true);


--
-- Name: production_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.production_orders_id_seq', 1, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 3, true);


--
-- Name: specifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.specifications_id_seq', 3, true);


--
-- Name: units_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.units_id_seq', 3, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- Name: counterparties counterparties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counterparties
    ADD CONSTRAINT counterparties_pkey PRIMARY KEY (id);


--
-- Name: customer_order_items customer_order_items_order_id_product_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_order_items
    ADD CONSTRAINT customer_order_items_order_id_product_id_key UNIQUE (order_id, product_id);


--
-- Name: customer_order_items customer_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_order_items
    ADD CONSTRAINT customer_order_items_pkey PRIMARY KEY (id);


--
-- Name: customer_orders customer_orders_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_orders
    ADD CONSTRAINT customer_orders_number_key UNIQUE (number);


--
-- Name: customer_orders customer_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_orders
    ADD CONSTRAINT customer_orders_pkey PRIMARY KEY (id);


--
-- Name: departments departments_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_name_key UNIQUE (name);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: materials materials_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_code_key UNIQUE (code);


--
-- Name: materials materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: operations operations_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_code_key UNIQUE (code);


--
-- Name: operations operations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_pkey PRIMARY KEY (id);


--
-- Name: production_order_items production_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_order_items
    ADD CONSTRAINT production_order_items_pkey PRIMARY KEY (id);


--
-- Name: production_order_items production_order_items_production_order_id_specification_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_order_items
    ADD CONSTRAINT production_order_items_production_order_id_specification_id_key UNIQUE (production_order_id, specification_id);


--
-- Name: production_orders production_orders_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_orders
    ADD CONSTRAINT production_orders_number_key UNIQUE (number);


--
-- Name: production_orders production_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_orders
    ADD CONSTRAINT production_orders_pkey PRIMARY KEY (id);


--
-- Name: products products_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_code_key UNIQUE (code);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: products products_production_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_production_code_key UNIQUE (production_code);


--
-- Name: specification_materials specification_materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specification_materials
    ADD CONSTRAINT specification_materials_pkey PRIMARY KEY (specification_id, material_id);


--
-- Name: specification_operations specification_operations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specification_operations
    ADD CONSTRAINT specification_operations_pkey PRIMARY KEY (specification_id, operation_id);


--
-- Name: specifications specifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specifications
    ADD CONSTRAINT specifications_pkey PRIMARY KEY (id);


--
-- Name: specifications specifications_product_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specifications
    ADD CONSTRAINT specifications_product_id_key UNIQUE (product_id);


--
-- Name: units units_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_name_key UNIQUE (name);


--
-- Name: units units_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_login_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_login_unique ON public.users USING btree (lower((login)::text));


--
-- Name: customer_order_items customer_order_items_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_order_items
    ADD CONSTRAINT customer_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.customer_orders(id);


--
-- Name: customer_order_items customer_order_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_order_items
    ADD CONSTRAINT customer_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: customer_orders customer_orders_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_orders
    ADD CONSTRAINT customer_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.counterparties(id);


--
-- Name: customer_orders customer_orders_executor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_orders
    ADD CONSTRAINT customer_orders_executor_id_fkey FOREIGN KEY (executor_id) REFERENCES public.counterparties(id);


--
-- Name: materials materials_unit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id);


--
-- Name: notes notes_id_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_id_user_fkey FOREIGN KEY (id_user) REFERENCES public.users(id);


--
-- Name: operations operations_unit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id);


--
-- Name: production_order_items production_order_items_production_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_order_items
    ADD CONSTRAINT production_order_items_production_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES public.production_orders(id);


--
-- Name: production_order_items production_order_items_specification_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_order_items
    ADD CONSTRAINT production_order_items_specification_id_fkey FOREIGN KEY (specification_id) REFERENCES public.specifications(id);


--
-- Name: production_orders production_orders_customer_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_orders
    ADD CONSTRAINT production_orders_customer_order_id_fkey FOREIGN KEY (customer_order_id) REFERENCES public.customer_orders(id);


--
-- Name: production_orders production_orders_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_orders
    ADD CONSTRAINT production_orders_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: production_orders production_orders_executor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.production_orders
    ADD CONSTRAINT production_orders_executor_user_id_fkey FOREIGN KEY (executor_user_id) REFERENCES public.users(id);


--
-- Name: products products_unit_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id);


--
-- Name: specification_materials specification_materials_material_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specification_materials
    ADD CONSTRAINT specification_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id);


--
-- Name: specification_materials specification_materials_specification_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specification_materials
    ADD CONSTRAINT specification_materials_specification_id_fkey FOREIGN KEY (specification_id) REFERENCES public.specifications(id);


--
-- Name: specification_operations specification_operations_operation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specification_operations
    ADD CONSTRAINT specification_operations_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.operations(id);


--
-- Name: specification_operations specification_operations_specification_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specification_operations
    ADD CONSTRAINT specification_operations_specification_id_fkey FOREIGN KEY (specification_id) REFERENCES public.specifications(id);


--
-- Name: specifications specifications_manufacturer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specifications
    ADD CONSTRAINT specifications_manufacturer_id_fkey FOREIGN KEY (manufacturer_id) REFERENCES public.counterparties(id);


--
-- Name: specifications specifications_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specifications
    ADD CONSTRAINT specifications_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- PostgreSQL database dump complete
--


