<script setup>
import {computed,ref,watch,onMounted,onUnmounted} from 'vue'
import {Plus,Save,Upload,Download,Eye,FilePenLine,Copy,Trash2,GitPullRequest,CheckCircle2} from 'lucide-vue-next'
import {clone,newCourse,newLesson,copyEdition,validateCatalog,editableCatalog} from '../content/catalog.js'
import {createGitHubClient,repositoryUrl,assetPath,bytesBase64,MAX_FILE_BYTES,validateAssets} from '../services/github-content.js'
import {readDraft,writeDraft,deleteDraft} from '../services/drafts.js'
import LessonBlocks from './LessonBlocks.vue'
import BlockEditor from './BlockEditor.vue'
import EditorGuide from './EditorGuide.vue'
const props=defineProps({catalog:Object})
const draft=ref(clone(props.catalog)),assets=ref([]),year=ref(props.catalog.currentYear),courseId=ref(draft.value.editions.find(e=>e.year===year.value).courses[0]?.id||''),lessonId=ref('')
const edition=computed(()=>draft.value.editions.find(e=>e.year===year.value))
const course=computed(()=>edition.value?.courses.find(c=>c.id===courseId.value))
const lesson=computed(()=>course.value?.lessons.find(l=>l.id===lessonId.value))
const years=computed(()=>[...draft.value.editions].sort((a,b)=>b.year-a.year))
const errors=computed(()=>validateCatalog(draft.value))
const token=ref(''),busy=ref(false),connection=ref(''),notice=ref(''),error=ref(''),saved=ref(''),preview=ref(false),previewDb=ref('postgres'),savedDraft=ref(null),unlockArchive=ref(false),newYear=ref(props.catalog.currentYear+1),copyYear=ref(true),newId=ref(''),title=ref('Обновление заданий демоэкзамена'),result=ref(null),recovery=ref(null)
const locked=computed(()=>year.value<draft.value.currentYear&&!unlockArchive.value)
let client=null,base=null,timer=null,ready=false,alive=true
const needsRefresh=ref(false)
const baseline=ref(JSON.stringify(draft.value))
const dirty=computed(()=>JSON.stringify(draft.value)!==baseline.value||assets.value.length>0)
const advancedGlossary=ref(''),advancedCodes=ref('')
watch(course,()=>{lessonId.value=course.value?.lessons[0]?.id||'';advancedGlossary.value=JSON.stringify(course.value?.glossary||[],null,2);advancedCodes.value=JSON.stringify(course.value?.codes||{},null,2);preview.value=false},{immediate:true})
watch(year,()=>{courseId.value=edition.value?.courses[0]?.id||'';unlockArchive.value=false})
watch([draft,assets],()=>{if(!ready)return;clearTimeout(timer);saved.value='Сохраняем черновик…';timer=setTimeout(saveDraft,600)},{deep:true})
function capture(){return {catalog:clone(draft.value),assets:clone(assets.value),base:base?clone(base):null,timestamp:Date.now()}}
async function saveDraft(){try{await writeDraft(capture());saved.value='Черновик сохранён в этом браузере'}catch{saved.value='Браузер не сохранил черновик. Скачайте резервную копию.'}}
function changeData(data,pending=[],loadedBase=null){ready=false;clearTimeout(timer);draft.value=clone(data);assets.value=clone(pending);base=loadedBase;year.value=data.currentYear;courseId.value=data.editions.find(e=>e.year===data.currentYear)?.courses[0]?.id||'';ready=true;preview.value=false}
function restore(){const value=savedDraft.value;if(!value)return;changeData(value.catalog,value.assets||[],value.base||null);savedDraft.value=null;notice.value='Локальный черновик восстановлен';saveDraft()}
async function discardStored(){await deleteDraft();savedDraft.value=null;notice.value='Сохранённый черновик удалён';ready=true;if(dirty.value)saveDraft()}
function addYear(){try{if(copyYear.value)copyEdition(draft.value,year.value,Number(newYear.value));else {const y=Number(newYear.value);if(!Number.isInteger(y)||y<2020||y>2100||draft.value.editions.some(e=>e.year===y))throw new Error('Этот год уже есть или введён неверно');draft.value.editions.push({year:y,courses:[]})}year.value=Number(newYear.value);newYear.value=year.value+1;notice.value='Создан выпуск. Скопированные направления стали черновиками; проверьте условия, КИМ, код и файлы.';error.value=''}catch(e){error.value=e.message}}
function addCourse(){if(locked.value)return false;const id=newId.value.trim();if(!/^[a-z][a-z0-9-]{0,63}$/.test(id)||['admin','archive','specialties','year'].includes(id)||edition.value.courses.some(c=>c.id===id)){error.value='Введите свободный ID латиницей, например network-admin';return false}edition.value.courses.push(newCourse(id));courseId.value=id;newId.value='';error.value='';return true}
function copyCourse(){if(!course.value)return;const original=clone(course.value);if(!addCourse())return;const id=courseId.value;original.id=id;original.status='draft';original.title+=' (копия)';const index=edition.value.courses.findIndex(c=>c.id===id);edition.value.courses[index]=original}
function deleteCourse(){if(locked.value||!course.value)return;if(!window.confirm(`Удалить направление «${course.value.title}» из выпуска ${year.value}?`))return;edition.value.courses=edition.value.courses.filter(c=>c.id!==courseId.value);courseId.value=edition.value.courses[0]?.id||''}
function makeCurrent(){if(!edition.value.courses.some(c=>c.status==='published')){error.value='Сначала опубликуйте хотя бы одно направление этого года';return}if(errors.value.length){error.value='Сначала исправьте ошибки каталога';return}if(!window.confirm(`Сделать ${year.value} текущим годом? Выпуск ${draft.value.currentYear} останется в архиве.`))return;draft.value.currentYear=year.value;notice.value=`Текущий выпуск: ${year.value}. Другие годы остаются в архиве.`}
function addLesson(){const ids=new Set(course.value.lessons.map(l=>l.id));let n=1;while(ids.has(`task-${n}`))n++;const l=newLesson(`task-${n}`,String(course.value.lessons.filter(l=>l.id!=='setup').length+1).padStart(2,'0'));course.value.lessons.push(l);lessonId.value=l.id}
function deleteLesson(){if(!window.confirm(`Удалить задание «${lesson.value.title}»?`))return;course.value.lessons=course.value.lessons.filter(l=>l!==lesson.value);lessonId.value=course.value.lessons[0]?.id||''}
function move(list,index,delta){const next=index+delta;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]]}
function addPreparation(){if(course.value.lessons.some(l=>l.id==='setup'))return;const l=newLesson('setup','00');l.title='Подготовить рабочее место';l.tag='Подготовка';l.icon='Settings';course.value.lessons.unshift(l);lessonId.value='setup'}
function addSection(){let n=1;while(lesson.value.sections.some(s=>s.id===`section-${n}`))n++;lesson.value.sections.push({id:`section-${n}`,title:'Новый раздел',blocks:[{type:'p',text:''}]})}
function applyAdvanced(){try{const glossary=JSON.parse(advancedGlossary.value),codes=JSON.parse(advancedCodes.value);const candidate=clone(draft.value);const target=candidate.editions.find(e=>e.year===year.value).courses.find(c=>c.id===courseId.value);target.glossary=glossary;target.codes=codes;const before=new Set(errors.value);const extra=validateCatalog(candidate).filter(e=>!before.has(e));if(extra.length)throw new Error(extra.slice(0,3).join('; '));course.value.glossary=glossary;course.value.codes=codes;error.value='';notice.value='Словарь и примеры кода обновлены'}catch(e){error.value='JSON не применён: '+e.message}}
function downloadBackup(){const blob=new Blob([JSON.stringify({kind:'spravka-backup',version:1,...(savedDraft.value||capture())},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`spravka-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importBackup(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>100*1024*1024)throw new Error('Резервная копия больше 100 МБ');const value=JSON.parse(await file.text()),data=value.kind==='spravka-backup'?value.catalog:value,pending=value.kind==='spravka-backup'?value.assets||[]:[];const issues=validateCatalog(data);if(!editableCatalog(data)||(value.kind!=='spravka-backup'&&issues.length))throw new Error(issues.slice(0,5).join('; ')||'Некорректная структура каталога');validateAssets(pending);if(!window.confirm('Заменить открытый каталог резервной копией? Сначала экспортируйте нужные несохранённые правки.'))return;changeData(data,pending,base);savedDraft.value=null;await saveDraft();error.value='';notice.value='Резервная копия загружена в редактор. Публичный сайт ещё не изменён.'}catch(e){error.value='Импорт не выполнен: '+e.message}}
async function uploadFile(event){const file=event.target.files?.[0];event.target.value='';if(!file||locked.value)return;try{if(assets.value.length>=20)throw new Error('За одну отправку допустимо 20 файлов');if(file.size<1||file.size>MAX_FILE_BYTES)throw new Error('Файл должен быть не пустым и не больше 10 МБ');if(!/\.(pdf|zip|docx|xlsx|xls|csv|json|sql|cs|xaml|txt|md|drawio|png|jpg|jpeg|webp)$/i.test(file.name))throw new Error('Поддерживаются PDF, ZIP, DOCX, XLSX, XLS, CSV, JSON, SQL, C#, XAML, TXT, MD, DRAWIO и изображения PNG/JPG/WebP');const target=course.value,path=assetPath(year.value,target.id,file.name),content=bytesBase64(new Uint8Array(await file.arrayBuffer()));assets.value.push({path,content,size:file.size});target.resources.push({url:path.replace(/^public\//,''),title:file.name,description:'',type:file.name.split('.').at(-1).toUpperCase()});notice.value='Файл добавлен в черновик. Он появится на сайте после слияния pull request.';error.value=''}catch(e){error.value=e.message}}
function removeResource(index){const r=course.value.resources[index];course.value.resources.splice(index,1);if(course.value.download===r.url)course.value.download='';if(!draft.value.editions.some(e=>e.courses.some(c=>c.download===r.url||c.resources.some(item=>item.url===r.url))))assets.value=assets.value.filter(a=>a.path!==`public/${r.url}`)}
async function connect(){busy.value=true;error.value='';try{const previousBase=base;client=createGitHubClient(token.value);const loaded=await client.load();needsRefresh.value=JSON.stringify(loaded.data)!==baseline.value&&loaded.baseHead!==previousBase?.baseHead;base={baseHead:loaded.baseHead,branch:loaded.branch,fileSha:loaded.fileSha};connection.value=`Подключено: siers22/spravka · ${loaded.branch}`;notice.value=needsRefresh.value?'Сайт отстаёт от каталога на GitHub. Экспортируйте правки и загрузите актуальный каталог перед отправкой.':'Доступ проверен. Можно загрузить каталог с GitHub или отправить открытый черновик.'}catch(e){client=null;base=null;connection.value='';error.value=e.message}finally{busy.value=false;token.value=''}}
async function loadRemote(){if(dirty.value&&!window.confirm('Загрузить каталог с GitHub вместо открытого черновика? Сначала скачайте резервную копию нужных правок.'))return;busy.value=true;try{const loaded=await client.load();base={baseHead:loaded.baseHead,branch:loaded.branch,fileSha:loaded.fileSha};changeData(loaded.data,[],base);baseline.value=JSON.stringify(loaded.data);needsRefresh.value=false;savedDraft.value=null;result.value=null;recovery.value=null;await saveDraft();notice.value='Актуальный каталог с GitHub открыт';error.value=''}catch(e){error.value=e.message}finally{busy.value=false}}
function disconnect(){client=null;base=null;connection.value='';token.value='';notice.value='GitHub отключён'}
async function publish(){if(needsRefresh.value||savedDraft.value)return;busy.value=true;error.value='';result.value=null;recovery.value=null;try{result.value=await client.publish(clone(draft.value),base,clone(assets.value),title.value);notice.value='Pull request создан. Откройте его, проверьте изменения и дождитесь проверок. После слияния обновится сайт.'}catch(e){error.value=e.message;if(e.branchUrl)recovery.value={branchUrl:e.branchUrl,compareUrl:e.compareUrl}}finally{busy.value=false}}
function beforeUnload(event){if(dirty.value){event.preventDefault();event.returnValue=''}}
onMounted(async()=>{try{const stored=await readDraft();if(!alive)return;if(stored?.catalog){validateAssets(stored.assets||[]);if(editableCatalog(stored.catalog)&&(JSON.stringify(stored.catalog)!==JSON.stringify(props.catalog)||stored.assets?.length))savedDraft.value=stored}}catch{saved.value='Хранилище черновиков недоступно — используйте экспорт'}finally{if(alive)ready=!savedDraft.value}window.addEventListener('beforeunload',beforeUnload)})
onUnmounted(()=>{alive=false;clearTimeout(timer);if(ready&&dirty.value)writeDraft(capture()).catch(()=>{});token.value='';client=null;window.removeEventListener('beforeunload',beforeUnload)})
const fieldNames={title:'Название направления',short:'Короткое название',kim:'Номер КИМ',domain:'Предметная область',subtitle:'Подзаголовок обзора',description:'Описание',stack:'Технологии / стек',paTime:'Время ПА',giaTime:'Время ГИА',verification:'Что проверено в примере',download:'Ссылка на основной файл (путь или https://)',downloadLabel:'Подпись кнопки скачивания',downloadType:'Тип основного файла (ZIP, PDF…)'}
const lessonFields={title:'Название задания',short:'Краткая подпись',number:'Номер',tag:'Метка',summary:'Суть задания',deliverable:'Результат для сдачи',source:'Источник / страницы КИМ'}
</script>
<template>
<div class="catalog-page editor-page"><EditorGuide :current-year="catalog.currentYear"/><div class="page-heading"><div class="eyebrow"><FilePenLine :size="16"/> УПРАВЛЕНИЕ МЕТОДИЧКОЙ</div><h1>Редактор заданий.</h1><p class="page-subtitle">Новые годы, направления и задания. Черновик хранится в браузере; публикация требует права записи на GitHub.</p></div>
<div v-if="savedDraft" class="catalog-notice draft-recovery"><b>Есть сохранённый черновик от {{new Date(savedDraft.timestamp).toLocaleString('ru')}}</b><button @click="restore">Восстановить черновик</button><button @click="discardStored">Удалить сохранённый черновик</button></div>
<div class="editor-toolbar"><button :disabled="busy" @click="downloadBackup"><Download :size="16"/>Скачать резервную копию</button><label class="editor-file"><Upload :size="16"/>Импорт JSON<input type="file" accept=".json" :disabled="busy||!!savedDraft" @change="importBackup"></label><button :disabled="busy||!!savedDraft" @click="saveDraft"><Save :size="16"/>Сохранить черновик</button><span role="status">{{saved}}</span></div>
<p v-if="notice" role="status" class="editor-status">{{notice}}</p><p v-if="error" role="alert" class="editor-error">{{error}}</p>
<details class="editor-panel github-panel"><summary><GitPullRequest :size="18"/> Сохранение на GitHub</summary><p>Данные и файлы хранятся в <a :href="repositoryUrl" target="_blank" rel="noopener">репозитории siers22/spravka</a>. Редактор создаёт отдельную ветку и pull request. После его слияния в основную ветку GitHub Pages собирает сайт.</p><p>Владелец или приглашённый редактор создаёт fine-grained token только для этого репозитория, с правами <b>Contents: read and write</b> и <b>Pull requests: read and write</b>. Token используется только в памяти страницы и удаляется при выходе из редактора.</p>
<template v-if="!connection"><label>GitHub token<input v-model="token" type="password" autocomplete="off" spellcheck="false" placeholder="github_pat_…" :disabled="busy"></label><button :disabled="busy||!token.trim()" @click="connect">{{busy?'Проверяем доступ…':'Подключиться к GitHub'}}</button></template><template v-else><p class="editor-status"><CheckCircle2 :size="16"/>{{connection}}</p><div class="editor-inline"><button :disabled="busy" @click="loadRemote">Загрузить актуальный каталог</button><button :disabled="busy" @click="disconnect">Отключиться</button></div><label>Название изменений<input v-model="title" :disabled="busy"></label><p v-if="errors.length" class="editor-error">Перед отправкой исправьте {{errors.length}} ошибок. Полный список — внизу редактора.</p><button class="editor-primary" :disabled="busy||!!errors.length||!dirty||!!savedDraft||!!result||needsRefresh" @click="publish"><GitPullRequest :size="16"/>{{busy?'Отправляем изменения…':'Создать pull request'}}</button><p>Открытый каталог отправляется целиком. Если основная ветка обновилась после подключения, редактор остановит отправку для защиты чужих правок.</p></template>
<p v-if="result" class="editor-status"><a :href="result.url" target="_blank" rel="noopener">Открыть созданный pull request →</a></p><p v-if="recovery" class="editor-error">Ветка уже сохранена, но pull request создать не удалось. <a :href="recovery.compareUrl" target="_blank" rel="noopener">Создать его из сохранённой ветки →</a></p>
</details>
<div class="editor-layout" :class="{'editor-paused':busy||!!savedDraft}"><aside class="editor-outline"><div class="editor-panel"><label>Выпуск<select v-model.number="year" aria-label="Выпуск"><option v-for="e in years" :key="e.year" :value="e.year">{{e.year}}{{e.year===draft.currentYear?' · текущий':''}}</option></select></label><button v-if="year!==draft.currentYear" @click="makeCurrent">Сделать текущим годом</button><p class="editor-help">Текущий год: {{draft.currentYear}}. Другие опубликованные выпуски доступны в архиве.</p><label v-if="year<draft.currentYear" class="editor-checkbox"><input v-model="unlockArchive" type="checkbox">Разрешить правки архивного выпуска</label><hr><label>Новый год<input v-model.number="newYear" type="number" min="2020" max="2100"></label><label class="editor-checkbox"><input v-model="copyYear" type="checkbox">Скопировать выбранный выпуск</label><button @click="addYear"><Plus :size="15"/>Добавить год</button></div>
<div class="editor-panel"><label>Направление<select v-model="courseId" aria-label="Направление"><option v-for="c in edition.courses" :key="c.id" :value="c.id">{{c.short||c.title}} · {{c.status==='draft'?'черновик':'опубликовано'}}</option></select></label><fieldset :disabled="locked"><label>ID нового направления<input v-model="newId" placeholder="network-admin"></label><button @click="addCourse"><Plus :size="15"/>Новое направление</button><button v-if="course" @click="copyCourse"><Copy :size="15"/>Копировать выбранное</button><button v-if="course" class="editor-danger" @click="deleteCourse"><Trash2 :size="15"/>Удалить направление</button></fieldset></div>
<div v-if="course" class="editor-panel"><b>Задания</b><button v-for="l in course.lessons" :key="l.id" :class="['editor-lesson-link',{selected:lessonId===l.id}]" @click="lessonId=l.id;preview=false">{{l.number}} · {{l.title}}</button><button v-if="!course.lessons.some(l=>l.id==='setup')" :disabled="locked" @click="addPreparation"><Plus :size="15"/>Добавить подготовку</button><button :disabled="locked" @click="addLesson"><Plus :size="15"/>Добавить задание</button></div></aside>
<div class="editor-workspace"><p v-if="locked" class="catalog-notice">Архивный выпуск защищён от случайных правок. Для нового года используйте копирование выпуска.</p><p v-if="!course" class="catalog-notice">Добавьте направление с уникальным ID. Изменения можно сохранить резервной копией.</p>
<template v-if="course"><details class="editor-panel" open><summary>Настройки направления · {{course.id}}</summary><fieldset :disabled="locked"><div class="editor-fields"><label v-for="(label,field) in fieldNames" :key="field">{{label}}<textarea v-if="['description','verification','subtitle'].includes(field)" v-model="course[field]" rows="2"/><input v-else v-model="course[field]"></label><label>Статус<select v-model="course.status" aria-label="Статус"><option value="draft">Черновик (не виден читателям)</option><option value="published">Опубликован в этом выпуске</option></select></label><label v-for="[field,label] in [['paCount','Заданий на ПА'],['paPoints','Баллов ПА'],['giaPoints','Баллов ГИА'],['pages','Страниц в КИМ']]" :key="field">{{label}}<input v-model.number="course[field]" type="number" min="0"></label><label class="editor-checkbox"><input v-model="course.dialectExamples" type="checkbox">Показывать учебный блок PostgreSQL / SQL Server</label></div></fieldset></details>
<details class="editor-panel"><summary>Файлы, исходные задания и приложения ({{course.resources.length}})</summary><fieldset :disabled="locked"><label class="editor-file"><Upload :size="16"/>Прикрепить файл (до 10 МБ)<input type="file" accept=".pdf,.zip,.docx,.xlsx,.xls,.csv,.json,.sql,.cs,.xaml,.txt,.md,.drawio,.png,.jpg,.jpeg,.webp" @change="uploadFile"></label><p class="editor-help">Файл получает новый адрес в папке своего года. При копировании выпуска ссылки ведут на прежние файлы — загрузите новое КИМ и приложения.</p><div v-for="(resource,index) in course.resources" :key="index" class="editor-resource"><div class="editor-fields"><label>Название<input v-model="resource.title"></label><label>Тип<input v-model="resource.type"></label><label>Путь или https://<input v-model="resource.url"></label><label>Описание<input v-model="resource.description"></label></div><div class="editor-inline"><button @click="course.download=resource.url;course.downloadType=resource.type">Использовать как основной пример</button><button class="editor-danger" @click="removeResource(index)">Убрать ссылку</button></div></div><button @click="course.resources.push({title:'Новый файл',type:'PDF',description:'',url:''})"><Plus :size="15"/>Добавить ссылку</button></fieldset></details>
<details class="editor-panel"><summary>Словарь и общие примеры кода (JSON)</summary><fieldset :disabled="locked"><label>Словарь: [["Термин", "Объяснение"]]<textarea v-model="advancedGlossary" rows="7" spellcheck="false" class="code-input"/></label><label>Код: {"ключ": "текст"} или {"ключ": {"postgres": "…", "mssql": "…"}}<textarea v-model="advancedCodes" rows="9" spellcheck="false" class="code-input"/></label><button @click="applyAdvanced">Применить словарь и код</button></fieldset></details>
<section v-if="lesson" class="editor-panel lesson-editor"><div class="editor-inline editor-between"><h2>{{lesson.number}} · {{lesson.title}}</h2><button @click="preview=!preview"><Eye :size="16"/>{{preview?'Вернуться к редактору':'Предпросмотр'}}</button></div>
<div v-if="preview" class="editor-preview"><label>Вариант кода<select v-model="previewDb" aria-label="Вариант кода"><option value="postgres">PostgreSQL</option><option value="mssql">SQL Server</option></select></label><h2>{{lesson.title}}</h2><p>{{lesson.summary}}</p><div v-for="section in lesson.sections" :key="section.id" class="lesson-section"><h3>{{section.title}}</h3><LessonBlocks :blocks="section.blocks" :db="previewDb" :code-set="course.codes" :resources="course.resources"/></div><h3>Чек-лист</h3><ul><li v-for="(item,i) in lesson.checks" :key="i">{{item}}</li></ul></div>
<fieldset v-else :disabled="locked"><div class="editor-fields"><label v-for="(label,field) in lessonFields" :key="field">{{label}}<textarea v-if="['summary','deliverable','source'].includes(field)" v-model="lesson[field]" rows="2"/><input v-else v-model="lesson[field]"></label><label>Минуты по КИМ<input v-model.number="lesson.time" type="number" min="0"></label><label>Иконка<select v-model="lesson.icon" aria-label="Иконка"><option v-for="icon in ['Settings','Network','Database','Calculator','LockKeyhole','Braces','FileText']" :key="icon">{{icon}}</option></select></label></div><p class="editor-help">ID задания: {{lesson.id}}. Он закрепляет ссылки и прогресс; при создании нового задания ID выдаётся автоматически.</p><label>Чек-лист: один пункт на строку<textarea :value="lesson.checks.join('\n')" rows="4" @input="lesson.checks=$event.target.value.split('\n')"/></label>
<div v-for="(section,si) in lesson.sections" :key="si" class="editor-section"><div class="editor-inline"><label>ID раздела<input v-model="section.id"></label><label>Заголовок<input v-model="section.title"></label></div><div class="editor-inline"><button :disabled="si===0" @click="move(lesson.sections,si,-1)">Выше</button><button :disabled="si===lesson.sections.length-1" @click="move(lesson.sections,si,1)">Ниже</button><button class="editor-danger" @click="lesson.sections.splice(si,1)">Удалить раздел</button></div><BlockEditor v-for="(block,bi) in section.blocks" :key="bi" :block="block" :codes="course.codes"><div class="editor-inline"><button :disabled="bi===0" @click="move(section.blocks,bi,-1)">↑<span class="sr-only">Поднять блок</span></button><button :disabled="bi===section.blocks.length-1" @click="move(section.blocks,bi,1)">↓<span class="sr-only">Опустить блок</span></button><button class="editor-danger" @click="section.blocks.splice(bi,1)">Удалить блок</button></div></BlockEditor><button @click="section.blocks.push({type:'p',text:''})"><Plus :size="15"/>Добавить блок</button></div><div class="editor-inline"><button @click="addSection"><Plus :size="15"/>Добавить раздел</button><button @click="move(course.lessons,course.lessons.indexOf(lesson),-1)">Задание выше</button><button @click="move(course.lessons,course.lessons.indexOf(lesson),1)">Задание ниже</button><button class="editor-danger" @click="deleteLesson">Удалить задание</button></div></fieldset></section></template>
<details v-if="errors.length" open class="editor-panel editor-validation"><summary>Исправьте перед публикацией: {{errors.length}}</summary><ul><li v-for="(issue,i) in errors.slice(0,30)" :key="i">{{issue}}</li></ul></details><p v-else class="editor-status"><CheckCircle2 :size="16"/>Каталог прошёл проверку</p>
</div></div></div>
</template>
