<script setup>
import { ref,computed } from 'vue'
import { RefreshCw,LockKeyhole,Info,CheckCircle2 } from 'lucide-vue-next'
import { publicUrl } from '../utils/public-url.js'
const tiles=ref([3,1,4,2]), selected=ref(null),login=ref('user'),password=ref(''),attempts=ref(0),blocked=ref(false),message=ref(''),success=ref(false)
const solved=computed(()=>tiles.value.every((tile,index)=>tile===index+1))
function swap(index){if(selected.value===null){selected.value=index;return}const previous=selected.value;[tiles.value[index],tiles.value[previous]]=[tiles.value[previous],tiles.value[index]];selected.value=null}
function shuffle(){tiles.value=[3,1,4,2];selected.value=null}
function submit(){success.value=false;if(!login.value||!password.value){message.value='Заполните логин и пароль';return}if(login.value!=='user'){message.value='Такого пользователя в тренажёре нет. Используйте user';return}if(blocked.value){message.value='Вы заблокированы. Обратитесь к администратору';return}
if(password.value!=='Test123!'||!solved.value){attempts.value++;if(attempts.value>=3){blocked.value=true;message.value='Вы заблокированы. Обратитесь к администратору'}else{message.value=!solved.value?'Пазл собран неверно. Поменяйте местами фрагменты.':'Вы ввели неверный логин или пароль. Пожалуйста проверьте ещё раз введенные данные'}return}
attempts.value=0;success.value=true;message.value='Вы успешно авторизовались'}
function reset(){attempts.value=0;blocked.value=false;message.value='Блокировка снята, счётчик сброшен';success.value=false;password.value='';shuffle()}
</script>
<template><div class="auth-lab"><div class="lab-heading"><span class="mini-tag">ТРЕНАЖЁР · В БРАУЗЕРЕ</span><span>Попробуйте ошибиться 3 раза</span></div><div class="auth-grid"><form @submit.prevent="submit"><label>Логин<input v-model="login" autocomplete="off" placeholder="user"></label><label>Пароль<input v-model="password" type="password" autocomplete="off" placeholder="Test123!"></label><div class="demo-puzzle"><button v-for="(tile,i) in tiles" :key="tile" type="button" @click="swap(i)" :class="{selected:selected===i}" :aria-pressed="selected===i" :aria-label="'Фрагмент '+tile+', позиция '+(i+1)"><img :src="publicUrl('sources/'+tile+'.png')" alt="Фрагмент пазла"></button></div><p class="quiet">Нажмите два фрагмента для обмена местами.</p><button class="btn primary" type="submit"><LockKeyhole :size="15"/>Войти</button></form><div class="auth-state"><h4>Что происходит в users</h4><div class="attempt-circles"><span v-for="i in 3" :key="i" :class="{filled:attempts>=i}">{{i}}</span></div><p>Ошибок подряд: <b>{{attempts}} / 3</b></p><p>is_blocked = <code>{{blocked?1:0}}</code></p><p>Пазл: <b>{{solved?'собран':'не собран'}}</b></p><div v-if="message" :class="['demo-message',{success}]" role="status"><CheckCircle2 v-if="success" :size="17"/><Info v-else :size="17"/><div><b>{{success?'Успех':blocked?'Блокировка':'Информация'}}</b><p>{{message}}</p></div></div><button @click="reset" class="text-button"><RefreshCw :size="14"/>Снять блокировку и начать заново</button><p class="quiet">Здесь логика показана на Vue без БД. В скачанном C#-проекте проверки и блокировка выполняются сервером. Пароль тренажёра: Test123!.</p></div></div></div></template>
