<script setup>
import {ref,computed} from 'vue'
import shoes from '../data/shoes.json'
import { publicUrl } from '../utils/public-url.js'
const date=ref('2026-05-15'),query=ref(''),category=ref(''),sort=ref('asc')
const categories=[...new Set(shoes.map(s=>s.category))]
const period=computed(()=>{const match=/^(\d{4})-(\d{2})-\d{2}$/.exec(date.value);if(!match)return null;const year=Number(match[1]),month=Number(match[2]);const previous=month===1?`${year-1}-12`:`${year}-${String(month-1).padStart(2,'0')}`;return {start:previous+'-01',end:`${year}-${String(month).padStart(2,'0')}-01`}})
const rows=computed(()=>shoes.map(s=>{const ordered=period.value&&s.orderedDates.some(d=>d>=period.value.start&&d<period.value.end);return {...s,discount:!ordered,final:Math.round(s.price*(ordered?1:.75)*100)/100}}).filter(s=>(!category.value||s.category===category.value)&&(`${s.name} ${s.description}`.toLocaleLowerCase('ru').includes(query.value.toLocaleLowerCase('ru')))).sort((a,b)=>sort.value==='desc'?b.final-a.final:a.final-b.final))
const money=value=>value.toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})
</script>
<template><div class="shoe-demo"><div class="demo-caption">ПОПРОБУЙТЕ НА ИСХОДНЫХ ДАННЫХ</div><h3>Когда модель получает скидку?</h3><label class="shoe-date">Дата расчёта<input type="date" v-model="date" min="2000-01-01" max="2099-12-31"></label><p v-if="period">Проверяем заказы: {{period.start}} ≤ дата &lt; {{period.end}}</p><p v-else>Укажите дату, чтобы увидеть период скидки.</p><div class="shoe-filters"><label>Поиск<input v-model="query" placeholder="Название или описание"></label><label>Категория<select v-model="category"><option value="">Все категории</option><option v-for="c in categories" :key="c">{{c}}</option></select></label><label>Цена<select v-model="sort"><option value="asc">По возрастанию</option><option value="desc">По убыванию</option></select></label></div><p class="quiet">Найдено {{rows.length}} из 31 модели · прокрутите список</p><div class="shoe-preview-list"><div v-for="shoe in rows" :key="shoe.id" :class="['shoe-preview',{low:shoe.available<=3}]"><img :src="publicUrl('shoes/'+shoe.image)" alt="" loading="lazy" @error="$event.target.src=publicUrl('shoes/picture.png')"><div><small>{{shoe.category}} · {{shoe.manufacturer}}</small><b>{{shoe.name}}</b><span>Остаток: {{shoe.available}} · {{shoe.available>5?'много':'мало'}}</span></div><div class="shoe-price"><b>{{money(shoe.final)}} ₽</b><span>{{shoe.discount?'Скидка 25%':'Без скидки'}}</span></div></div><p v-if="!rows.length">Совпадений нет. Измените поиск или категорию.</p></div></div></template>
