BEGIN;

CREATE TABLE roles (
    id integer PRIMARY KEY,
    name varchar(80) NOT NULL UNIQUE
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name varchar(80) NOT NULL,
    first_name varchar(80) NOT NULL,
    middle_name varchar(80) NOT NULL,
    login varchar(80) NOT NULL UNIQUE,
    role_id integer NOT NULL REFERENCES roles(id) ON DELETE RESTRICT
);

CREATE TABLE categories (
    id integer PRIMARY KEY,
    name varchar(80) NOT NULL UNIQUE
);

CREATE TABLE subcategories (
    id integer PRIMARY KEY,
    category_id integer NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    name varchar(80) NOT NULL,
    UNIQUE (category_id, name)
);

CREATE TABLE manufacturers (
    id integer PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subcategory_id integer NOT NULL REFERENCES subcategories(id) ON DELETE RESTRICT,
    manufacturer_id integer NOT NULL REFERENCES manufacturers(id) ON DELETE RESTRICT,
    image_name varchar(200),
    name varchar(200) NOT NULL,
    description text NOT NULL,
    composition text NOT NULL,
    price numeric(12,2) NOT NULL CHECK (price >= 0),
    UNIQUE (name, manufacturer_id)
);

CREATE TABLE sizes (
    id integer PRIMARY KEY,
    value numeric(4,1) NOT NULL UNIQUE CHECK (value > 0)
);

CREATE TABLE stock_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    size_id integer NOT NULL REFERENCES sizes(id) ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity >= 0),
    UNIQUE (product_id, size_id)
);

CREATE TABLE orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date date NOT NULL,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    stock_item_id integer NOT NULL REFERENCES stock_items(id) ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    UNIQUE (order_id, stock_item_id)
);

CREATE INDEX ix_order_items_stock ON order_items(stock_item_id);
CREATE INDEX ix_orders_date ON orders(order_date);
COMMIT;
