-- Выполнить один раз в пустой базе shoe_store.
CREATE TABLE categories (id int PRIMARY KEY, name varchar(100) NOT NULL UNIQUE);
CREATE TABLE subcategories (
 id int PRIMARY KEY, category_id int NOT NULL REFERENCES categories(id),
 name varchar(100) NOT NULL, UNIQUE(category_id,name)
);
CREATE TABLE manufacturers (id int PRIMARY KEY, name varchar(200) NOT NULL UNIQUE);
CREATE TABLE products (
 id int PRIMARY KEY, subcategory_id int NOT NULL REFERENCES subcategories(id),
 manufacturer_id int NOT NULL REFERENCES manufacturers(id), name varchar(300) NOT NULL,
 image_path varchar(200) NOT NULL, description varchar(2000) NOT NULL,
 composition varchar(2000) NOT NULL, base_price decimal(18,2) NOT NULL CHECK(base_price>=0),
 UNIQUE(manufacturer_id,name)
);
CREATE TABLE sizes (size decimal(3,1) PRIMARY KEY);
CREATE TABLE stock_items (
 id int PRIMARY KEY, product_id int NOT NULL REFERENCES products(id),
 size decimal(3,1) NOT NULL REFERENCES sizes(size), available_quantity int NOT NULL CHECK(available_quantity>=0),
 UNIQUE(product_id,size)
);
CREATE TABLE users (
 id int PRIMARY KEY, login varchar(100) NOT NULL UNIQUE,
 last_name varchar(100) NOT NULL, first_name varchar(100) NOT NULL, patronymic varchar(100) NOT NULL,
 role varchar(20) NOT NULL CHECK(role IN ('Admin','Manager','User'))
);
CREATE TABLE orders (
 id int PRIMARY KEY, order_date date NOT NULL, user_id int NOT NULL REFERENCES users(id)
);
CREATE TABLE order_items (
 id int PRIMARY KEY, order_id int NOT NULL REFERENCES orders(id),
 stock_item_id int NOT NULL REFERENCES stock_items(id), quantity int NOT NULL CHECK(quantity>0),
 unit_price decimal(18,2) NOT NULL CHECK(unit_price>=0), UNIQUE(order_id,stock_item_id)
);

-- Исходные XLSX: нормализованы пробелы и сопоставлено сокращённое название модели.
-- Stock_Items уже содержит доступные остатки. Старые заказы повторно не списываются.
BEGIN;
INSERT INTO categories VALUES(1,'Детская обувь');
INSERT INTO categories VALUES(2,'Женская обувь');
INSERT INTO categories VALUES(3,'Мужская обувь');
INSERT INTO subcategories VALUES(1,1,'Кроссовки');
INSERT INTO subcategories VALUES(2,1,'Сапоги');
INSERT INTO subcategories VALUES(3,1,'Босоножки');
INSERT INTO subcategories VALUES(4,1,'Туфли');
INSERT INTO subcategories VALUES(5,2,'Сапоги');
INSERT INTO subcategories VALUES(6,2,'Босоножки');
INSERT INTO subcategories VALUES(7,2,'Туфли');
INSERT INTO subcategories VALUES(8,2,'Кроссовки');
INSERT INTO subcategories VALUES(9,3,'Кроссовки');
INSERT INTO subcategories VALUES(10,3,'Туфли');
INSERT INTO subcategories VALUES(11,3,'Ботинки');
INSERT INTO manufacturers VALUES(1,'Малыш-Спорт');
INSERT INTO manufacturers VALUES(2,'Топ-Топ');
INSERT INTO manufacturers VALUES(3,'Лапушка');
INSERT INTO manufacturers VALUES(4,'Тёплые ножки');
INSERT INTO manufacturers VALUES(5,'Северята');
INSERT INTO manufacturers VALUES(6,'Весна');
INSERT INTO manufacturers VALUES(7,'Здоровый шаг');
INSERT INTO manufacturers VALUES(8,'Карапуз');
INSERT INTO manufacturers VALUES(9,'Маленький франт');
INSERT INTO manufacturers VALUES(10,'Барбари');
INSERT INTO manufacturers VALUES(11,'Твой комфорт');
INSERT INTO manufacturers VALUES(12,'Стиль и комфорт');
INSERT INTO manufacturers VALUES(13,'Кожевенные традиции');
INSERT INTO manufacturers VALUES(14,'Модный силуэт');
INSERT INTO manufacturers VALUES(15,'Азимут');
INSERT INTO manufacturers VALUES(16,'Берестов');
INSERT INTO products VALUES(1,1,1,'Кроссовки детские «Звёздочка» экокожа','IMG_KS_195217.png','Кроссовки детские «Звёздочка» экокожа. Производитель: ООО «Малыш-Спорт», г. Смоленск','Верх — экокожа (полиуретан на хлопковой основе), подкладка — хлопок 100%, подошва — ПВХ',2190);
INSERT INTO products VALUES(2,1,2,'Кроссовки детские «Гонщик» экокожа','IMG_KS_195213.png','Кроссовки детские «Гонщик» экокожа. Производитель: Фабрика «Топ-Топ», г. Киров','Верх — экокожа (микрофибра), подкладка — текстиль сетчатый (полиэстер), подошва — термопластичная резина (ТЭП)',2490);
INSERT INTO products VALUES(3,1,3,'Кроссовки детские «Радуга» экокожа перфорированная','IMG_KS_195222.png','Кроссовки детские «Радуга» экокожа перфорированная. Производитель: ИП Смирнова Л.В. (бренд «Лапушка»), г. Вологда','Верх — экокожа перфорированная, вставки — нейлон, стелька — ортопедическая с латексной подушкой, подошва — ЭВА',1990);
INSERT INTO products VALUES(4,2,4,'Сапожки детские «Снежинка» зимние на меху','IMG_KB_185501.png','Сапожки детские «Снежинка» зимние на меху. Производитель: ООО «Тёплые ножки», г. Новосибирск','Верх — экокожа морозостойкая, утеплитель — искусственный мех (акрил 70%, полиэстер 30%), подкладка — флис, подошва — термоэластопласт (ТЭП)',3490);
INSERT INTO products VALUES(5,2,5,'Сапожки детские «Медвежонок» демисезонные непромокаемые','IMG_KB_164816.png','Сапожки детские «Медвежонок» демисезонные непромокаемые. Производитель: Компания «Северята», г. Архангельск','Верх — плащёвая ткань с водоотталкивающей пропиткой (полиэстер 100%), отделка — экокожа, подкладка — микрофибра, мембрана — AirTex, подошва — резина',3190);
INSERT INTO products VALUES(6,2,6,'Сапожки детские «Принцесса» кожаные','IMG_KB_164811.png','Сапожки детские «Принцесса» кожаные. Производитель: Мастерская «Весна», г. Тула','Верх — натуральная кожа (КРС), подкладка — шерсть натуральная (70%), байка (30%), стелька — войлочная, подошва — полиуретан',4290);
INSERT INTO products VALUES(7,3,7,'Сандалии детские «Пчёлка» ортопедические летние','IMG_KSd_195207.png','Сандалии детские «Пчёлка» ортопедические летние. Производитель: ООО «Здоровый шаг», г. Воронеж','Верх — нубук натуральный, подкладка — кожа растительного дубления, стелька — анатомическая с супинатором (латекс + пробка), подошва — каучук',2790);
INSERT INTO products VALUES(8,3,8,'Сандалии детские «Морячок» текстильные с фиксатором','IMG_KSd_185508.png','Сандалии детские «Морячок» текстильные с фиксатором. Производитель: ИП Кузнецов А.Д. (бренд «Карапуз»), г. Краснодар','Верх — джинсовая ткань (хлопок 100%), окантовка — искусственная кожа, подкладка — хлопок, подошва — ЭВА лёгкая',1690);
INSERT INTO products VALUES(9,4,9,'Туфли детские «Бантик» лаковые праздничные','IMG_KSho_185512.png','Туфли детские «Бантик» лаковые праздничные. Производитель: Дом обуви «Маленький франт», г. Москва','Верх — искусственная лаковая кожа (ПВХ), носок усиленный — термопластичный полиуретан, подкладка — кожа искусственная дышащая, стелька — анатомическая с амортизацией, подошва — полиуретан',2390);
INSERT INTO products VALUES(10,5,10,'Сапоги зимние натуральная кожа','IMG_WB_170905.png','Сапоги женские зимние, нескользящая, устойчивая подошва, натуральный мех. Производитель: Дом обуви «Барбари», г. Новороссийск ','Верх — натуральная кожа, подкладка — евромех, натуральный мех, текстильный утеплитель, подошва — резина',25000);
INSERT INTO products VALUES(11,5,10,'Сапоги осенние натуральная кожа','IMG_WB_170859.png','Сапоги женские демисезонные из высококачественной натуральной кожи. Производитель: Дом обуви «Барбари», г. Новороссийск ','Верх — натуральная кожа, подкладка — текстильный утеплитель, стелька — текстиль, подошва — ТПР',15000);
INSERT INTO products VALUES(12,5,11,'Сапоги трубы демисезонные замшевые','IMG_WB_170906.png','Сапоги женские демисезонные замшевые. Производитель: ОАО «Твой комфорт», г. Ярославль','Верх — натуральная замша, утепленные, тракторная подошва, стелька — байка, подошва — резина',17000);
INSERT INTO products VALUES(13,6,12,'Босоножки «Песчаный берег» коричневые','IMG_WSd_174332.png','Коричневая кожаная модель с открытым носком, боковой пряжкой и закрытым каблуком. Производитель: ИП «Стиль и комфорт», г. Санкт-Петербург','Верх — 100% козья кожа, подкладка — 100% кожа; подошва: 100% кожа',7500);
INSERT INTO products VALUES(14,6,13,'Женские босоножки «Черный кофе» со скульптурным каблуком','IMG_WSd_185156.png','Открытый носок и ремешок со сборной пряжкой, низкий каблук и резиновая подошва гарантируют комфорт. Производитель: ЗАО «Кожевенные традиции», г. Вятка','Верх — кожа собственного производств, подкладка — кожа; подошва: резина',5600);
INSERT INTO products VALUES(15,6,14,'Босоножки женские «Летний бриз»','IMG_WSd_185551.png','Босоножки женские кожаные белые, регулируемый ремешок, закрытый каблук и кожаная подошва. Производитель: ООО «Модный силуэт», г. Кострома','Верх — натуральная кожа, подкладка — натуральная кожа, подошва — кожа',7130);
INSERT INTO products VALUES(16,7,14,'Демисезонные туфли натуральная кожа','IMG_WSho_174409.png','Комфортные лаконичные лодочки, классический дизайна с современными акцентами. Производитель: ООО «Модный силуэт», г. Кострома','Верх — натуральная овечья кожа, подкладка и стелька — натуральная овечья кожа, подошва — резина',12340);
INSERT INTO products VALUES(17,7,13,'Туфли женские натуральная кожа с металлическими вставками','IMG_WSho_185202.png','Стильные туфли для весеннего и летнего сезона. Производитель: ЗАО «Кожевенные традиции», г. Вятка','Верх — натуральная телячьей кожа, металлическая пряжка, подкладка и стелька— натуральная овечья кожа, подошва — резина',7757);
INSERT INTO products VALUES(18,7,12,'Туфли классические лодочки натуральная кожа','IMG_WSho_185545.png','Модель из натуральной кожи, классический острый носок и изящная шпилька. Производитель: ИП «Стиль и комфорт», г. Санкт-Петербург','Верх — натуральная кожа, подкладка и стелька — натуральная кожа, подошва — тунит',7550);
INSERT INTO products VALUES(19,8,2,'Кроссовки белые с оранжевым и красным','IMG_WS_174110.png','Многослойный верх из кожи и текстиля. Производитель: Фабрика «Топ-Топ», г. Киров','Верх — 70% кожа, 30% текстиль, подкладка — текстиль, подошва — резина',9450);
INSERT INTO products VALUES(20,8,2,'Кроссовки летние кожаные','IMG_WS_185528.png','Уверенность на каждом шагу. Материал обеспечивает долговечность и комфорт при носке. Производитель: Фабрика «Топ-Топ», г. Киров','Верх — 87% кожа, 11% текстиль, 2% синтетика; подкладка: 100% текстиль; подошва: резина, пластик',8565);
INSERT INTO products VALUES(21,8,12,'Кроссовки кожаные','IMG_WS_185535.png','Кроссовки женские из натуральной кожи. Производитель: ИП «Стиль и комфорт», г. Санкт-Петербург','Верх — натуральная кожа, подкладка — кожа, подошва — полиуретан',8765);
INSERT INTO products VALUES(22,8,12,'Кроссовки «Стиль и комфорт»','IMG_WS_185538.png','Кроссовки женские из натуральной кожи и синтетических материалов, сетчатые вставки. Производитель: ИП «Стиль и комфорт», г. Санкт-Петербург','Верх — 70% кожа, 20% полиамид, 10% полиуретан; подкладка — текстиль, подошва — ТПУ',7795);
INSERT INTO products VALUES(23,9,15,'Кроссовки для бега «Драйв»','IMG_MS_185531.png','Сочетание стиля, комфорта и современных технологий. Производитель: Фабрика «Азимут», г. Санкт-Петербург','Верх —  сетка, подкладка — текстиль, подошва —  резина',6550);
INSERT INTO products VALUES(24,9,15,'Кроссовки «Азимут Бег»','IMG_MS_185532.png','Универсальный выбор для повседневного использования. Производитель: Фабрика «Азимут», г. Санкт-Петербург','Верх — 6% кожа, 29% текстиль, 15% полимерные материалы; подкладка — 100% текстиль; подошва — полимерные материалы, резина',7890);
INSERT INTO products VALUES(25,9,2,'Кроссовки','IMG_MS_185533.png','Кроссовки для мужчин, идеальное сочетание стиля и комфорта. Производитель: Фабрика «Топ-Топ», г. Киров','Верх — 56% кожа, 29% текстиль, 15% полимерные материалы; подкладка — 100% текстиль; подошва — полимерные материалы, резина',9567);
INSERT INTO products VALUES(26,10,10,'Черные туфли в классическом стиле — база для деловых образов','IMG_MSho_190514.png','Модель выполнена из натуральной кожи, на резиновой подошве. Производитель: Дом обуви «Барбари», г. Новороссийск ','Верх — натуральная кожа, подкладка — текстиль, стелька — натуральная кожа, подошва — резина',24569);
INSERT INTO products VALUES(27,10,16,'Туфли мужские светлые классика демисезонные','IMG_MSho_190518.png','Туфли на низком каблуке кожаные','Верх — натуральная кожа, подкладка — текстиль, стелька — натуральная кожа, подошва — ТЭП',10155);
INSERT INTO products VALUES(28,10,16,'Туфли из натуральной кожи','IMG_MSho_191612.png','Модель выполнена из натуральной кожи, на резиновой подошве, поддеживает классический и деловой стиль образов. Производитель: Дом обуви «Берестов», г. Москва','Верх — натуральная кожа, подкладка — натуральная кожа, стелька — натуральная кожа, подошва — резина',25625);
INSERT INTO products VALUES(29,11,10,'Ботинки мужские демисезонные','IMG_MB_174349.png','Ботинки из натуральной кожи темно-коричневого и черного цвета на шнурках. Производитель: Дом обуви «Берестов», г. Москва','Верх — натуральная кожа, подкладка — текстиль, подошва — искусственный материал',21500);
INSERT INTO products VALUES(30,11,13,'Ботинки черные из натуральной кожи','IMG_MB_191200.png','Ботинки представляют баланс традиций и современности. Выполнены из натуральной кожи насыщенного черного цвета. Производитель: ЗАО «Кожевенные традиции», г. Вятка','Верх — натуральная кожа, подкладка — ворсин, стелька — ворсин, подошва — тунит',14567);
INSERT INTO products VALUES(31,11,10,'Ботинки зимние классические','IMG_MB_191205.png','Выбор на каждый день — натуральная кожа, натуральный мех. Производитель: Дом обуви «Барбари», г. Новороссийск ','Верх — натуральная кожа, подкладка — натуральный мех, стелька — натуральный мех, подошва — ТЭП',15670);
INSERT INTO sizes VALUES(18);
INSERT INTO sizes VALUES(19);
INSERT INTO sizes VALUES(20);
INSERT INTO sizes VALUES(21);
INSERT INTO sizes VALUES(22);
INSERT INTO sizes VALUES(23);
INSERT INTO sizes VALUES(24);
INSERT INTO sizes VALUES(25);
INSERT INTO sizes VALUES(26);
INSERT INTO sizes VALUES(27);
INSERT INTO sizes VALUES(28);
INSERT INTO sizes VALUES(29);
INSERT INTO sizes VALUES(30);
INSERT INTO sizes VALUES(31);
INSERT INTO sizes VALUES(32);
INSERT INTO sizes VALUES(33);
INSERT INTO sizes VALUES(34);
INSERT INTO sizes VALUES(35);
INSERT INTO sizes VALUES(36);
INSERT INTO sizes VALUES('36.5');
INSERT INTO sizes VALUES(37);
INSERT INTO sizes VALUES('37.5');
INSERT INTO sizes VALUES(38);
INSERT INTO sizes VALUES('38.5');
INSERT INTO sizes VALUES(39);
INSERT INTO sizes VALUES('39.5');
INSERT INTO sizes VALUES(40);
INSERT INTO sizes VALUES('40.5');
INSERT INTO sizes VALUES(41);
INSERT INTO sizes VALUES('41.5');
INSERT INTO sizes VALUES(42);
INSERT INTO sizes VALUES('42.5');
INSERT INTO sizes VALUES(43);
INSERT INTO sizes VALUES(44);
INSERT INTO sizes VALUES(45);
INSERT INTO stock_items VALUES(1,1,20.0,20);
INSERT INTO stock_items VALUES(2,1,21.0,20);
INSERT INTO stock_items VALUES(3,1,22.0,20);
INSERT INTO stock_items VALUES(4,1,23.0,20);
INSERT INTO stock_items VALUES(5,1,24.0,20);
INSERT INTO stock_items VALUES(6,1,25.0,20);
INSERT INTO stock_items VALUES(7,2,33.0,2);
INSERT INTO stock_items VALUES(8,2,34.0,2);
INSERT INTO stock_items VALUES(9,3,19.0,30);
INSERT INTO stock_items VALUES(10,3,20.0,30);
INSERT INTO stock_items VALUES(11,4,19.0,15);
INSERT INTO stock_items VALUES(12,4,20.0,15);
INSERT INTO stock_items VALUES(13,5,21.0,5);
INSERT INTO stock_items VALUES(14,5,22.0,5);
INSERT INTO stock_items VALUES(15,5,23.0,5);
INSERT INTO stock_items VALUES(16,6,18.0,4);
INSERT INTO stock_items VALUES(17,6,19.0,4);
INSERT INTO stock_items VALUES(18,6,20.0,4);
INSERT INTO stock_items VALUES(19,7,21.0,4);
INSERT INTO stock_items VALUES(20,7,22.0,4);
INSERT INTO stock_items VALUES(21,7,23.0,4);
INSERT INTO stock_items VALUES(22,7,24.0,4);
INSERT INTO stock_items VALUES(23,8,27.0,7);
INSERT INTO stock_items VALUES(24,8,28.0,7);
INSERT INTO stock_items VALUES(25,8,29.0,7);
INSERT INTO stock_items VALUES(26,8,30.0,7);
INSERT INTO stock_items VALUES(27,9,18.0,7);
INSERT INTO stock_items VALUES(28,9,19.0,7);
INSERT INTO stock_items VALUES(29,9,20.0,7);
INSERT INTO stock_items VALUES(30,10,36.0,12);
INSERT INTO stock_items VALUES(31,10,37.0,12);
INSERT INTO stock_items VALUES(32,11,39.0,2);
INSERT INTO stock_items VALUES(33,11,40.0,2);
INSERT INTO stock_items VALUES(34,12,37.0,5);
INSERT INTO stock_items VALUES(35,12,39.0,5);
INSERT INTO stock_items VALUES(36,12,40.0,5);
INSERT INTO stock_items VALUES(37,13,36.0,10);
INSERT INTO stock_items VALUES(38,13,37.0,10);
INSERT INTO stock_items VALUES(39,13,38.0,10);
INSERT INTO stock_items VALUES(40,13,39.0,10);
INSERT INTO stock_items VALUES(41,13,40.0,10);
INSERT INTO stock_items VALUES(42,14,35.0,3);
INSERT INTO stock_items VALUES(43,15,37.0,23);
INSERT INTO stock_items VALUES(44,15,39.0,23);
INSERT INTO stock_items VALUES(45,15,40.0,23);
INSERT INTO stock_items VALUES(46,16,36.0,25);
INSERT INTO stock_items VALUES(47,16,37.0,25);
INSERT INTO stock_items VALUES(48,16,38.0,25);
INSERT INTO stock_items VALUES(49,17,36.0,4);
INSERT INTO stock_items VALUES(50,17,38.0,4);
INSERT INTO stock_items VALUES(51,17,39.0,4);
INSERT INTO stock_items VALUES(52,17,40.0,4);
INSERT INTO stock_items VALUES(53,18,35.0,9);
INSERT INTO stock_items VALUES(54,18,38.0,9);
INSERT INTO stock_items VALUES(55,19,35.0,2);
INSERT INTO stock_items VALUES(56,19,36.0,2);
INSERT INTO stock_items VALUES(57,20,37.0,5);
INSERT INTO stock_items VALUES(58,20,37.5,5);
INSERT INTO stock_items VALUES(59,20,38.0,5);
INSERT INTO stock_items VALUES(60,20,38.5,5);
INSERT INTO stock_items VALUES(61,21,35.0,16);
INSERT INTO stock_items VALUES(62,21,36.0,16);
INSERT INTO stock_items VALUES(63,21,38.0,16);
INSERT INTO stock_items VALUES(64,21,39.0,16);
INSERT INTO stock_items VALUES(65,22,35.0,3);
INSERT INTO stock_items VALUES(66,22,38.0,3);
INSERT INTO stock_items VALUES(67,23,41.5,18);
INSERT INTO stock_items VALUES(68,23,42.0,18);
INSERT INTO stock_items VALUES(69,23,42.5,18);
INSERT INTO stock_items VALUES(70,23,43.0,18);
INSERT INTO stock_items VALUES(71,24,38.0,50);
INSERT INTO stock_items VALUES(72,24,38.5,50);
INSERT INTO stock_items VALUES(73,24,39.0,50);
INSERT INTO stock_items VALUES(74,24,39.5,50);
INSERT INTO stock_items VALUES(75,24,40.0,50);
INSERT INTO stock_items VALUES(76,24,41.0,50);
INSERT INTO stock_items VALUES(77,25,41.0,3);
INSERT INTO stock_items VALUES(78,25,42.0,3);
INSERT INTO stock_items VALUES(79,25,44.0,3);
INSERT INTO stock_items VALUES(80,26,40.0,23);
INSERT INTO stock_items VALUES(81,26,41.0,23);
INSERT INTO stock_items VALUES(82,26,43.0,23);
INSERT INTO stock_items VALUES(83,27,42.0,15);
INSERT INTO stock_items VALUES(84,27,43.0,15);
INSERT INTO stock_items VALUES(85,27,44.0,15);
INSERT INTO stock_items VALUES(86,28,44.0,3);
INSERT INTO stock_items VALUES(87,29,41.0,1);
INSERT INTO stock_items VALUES(88,29,42.0,1);
INSERT INTO stock_items VALUES(89,30,42.0,20);
INSERT INTO stock_items VALUES(90,30,43.0,20);
INSERT INTO stock_items VALUES(91,31,41.0,30);
INSERT INTO stock_items VALUES(92,31,42.0,30);
INSERT INTO users VALUES(1,'isivanov','Иванов','Иван','Сергеевич','Admin');
INSERT INTO users VALUES(2,'papetrov','Петров','Пётр','Алексеевич','Manager');
INSERT INTO users VALUES(3,'asidorova','Сидорова','Анна','Дмитриевна','User');
INSERT INTO users VALUES(4,'ekuznetsova','Кузнецова','Екатерина','Андреевна','Manager');
INSERT INTO users VALUES(5,'dsmirnov','Смирнов','Дмитрий','Владимирович','User');
INSERT INTO users VALUES(6,'apopov','Попов','Алексей','Николаевич','Admin');
INSERT INTO users VALUES(7,'ovasileva','Васильева','Ольга','Игоревна','User');
INSERT INTO users VALUES(8,'psokolov','Соколов','Павел','Викторович','Manager');
INSERT INTO users VALUES(9,'tmikhailova','Михайлова','Татьяна','Юрьевна','User');
INSERT INTO users VALUES(10,'nnovikova','Новикова','Наталья','Сергеевна','Manager');
INSERT INTO users VALUES(11,'afedorov','Фёдоров','Андрей','Максимович','Admin');
INSERT INTO users VALUES(12,'smorozov','Морозов','Сергей','Павлович','User');
INSERT INTO users VALUES(13,'jvolkova','Волкова','Юлия','Александровна','Manager');
INSERT INTO users VALUES(14,'aalekseev','Алексеев','Артём','Евгеньевич','User');
INSERT INTO users VALUES(15,'ilebedeva','Лебедева','Ирина','Владимировна','User');
INSERT INTO users VALUES(16,'negorov','Егоров','Никита','Денисович','Manager');
INSERT INTO users VALUES(17,'epavlova','Павлова','Елена','Петровна','User');
INSERT INTO users VALUES(18,'rkozlov','Козлов','Роман','Олегович','Admin');
INSERT INTO users VALUES(19,'vstepanova','Степанова','Виктория','Романовна','Manager');
INSERT INTO users VALUES(20,'vnikolaev','Николаев','Владимир','Иванович','User');
INSERT INTO orders VALUES(1,'2026-04-02',3);
INSERT INTO orders VALUES(2,'2026-04-05',17);
INSERT INTO orders VALUES(3,'2026-04-08',7);
INSERT INTO orders VALUES(4,'2026-04-12',15);
INSERT INTO orders VALUES(5,'2026-04-18',12);
INSERT INTO orders VALUES(6,'2026-04-22',9);
INSERT INTO orders VALUES(7,'2026-04-25',14);
INSERT INTO orders VALUES(8,'2026-04-28',20);
INSERT INTO orders VALUES(9,'2026-05-05',5);
INSERT INTO orders VALUES(10,'2026-05-08',17);
INSERT INTO order_items VALUES(1,1,1,1,2190);
INSERT INTO order_items VALUES(2,1,20,1,2790);
INSERT INTO order_items VALUES(3,2,30,1,25000);
INSERT INTO order_items VALUES(4,2,39,1,7500);
INSERT INTO order_items VALUES(5,3,34,1,17000);
INSERT INTO order_items VALUES(6,3,57,1,8565);
INSERT INTO order_items VALUES(7,3,65,1,7795);
INSERT INTO order_items VALUES(8,4,50,1,7757);
INSERT INTO order_items VALUES(9,4,48,1,12340);
INSERT INTO order_items VALUES(10,4,44,1,7130);
INSERT INTO order_items VALUES(11,4,62,1,8765);
INSERT INTO order_items VALUES(12,4,32,1,15000);
INSERT INTO order_items VALUES(13,5,77,1,9567);
INSERT INTO order_items VALUES(14,5,87,1,21500);
INSERT INTO order_items VALUES(15,5,73,1,7890);
INSERT INTO order_items VALUES(16,6,80,1,24569);
INSERT INTO order_items VALUES(17,6,89,1,14567);
INSERT INTO order_items VALUES(18,6,91,1,15670);
INSERT INTO order_items VALUES(19,7,16,1,4290);
INSERT INTO order_items VALUES(20,7,2,2,2190);
INSERT INTO order_items VALUES(21,7,24,1,1690);
INSERT INTO order_items VALUES(22,8,86,1,25625);
INSERT INTO order_items VALUES(23,8,75,3,7890);
INSERT INTO order_items VALUES(24,8,70,2,6550);
INSERT INTO order_items VALUES(25,9,7,1,2490);
INSERT INTO order_items VALUES(26,9,14,2,3190);
INSERT INTO order_items VALUES(27,10,53,1,7550);
INSERT INTO order_items VALUES(28,10,43,1,7130);
INSERT INTO order_items VALUES(29,10,46,1,12340);
INSERT INTO order_items VALUES(30,10,61,2,8765);
COMMIT;
